STATE_METADATA = {
    "alabama": {"label": "Alabama", "abbr": "AL", "country_scope": "us", "lat": 32.8, "lon": -86.8},
    "alaska": {"label": "Alaska", "abbr": "AK", "country_scope": "us", "lat": 64.2, "lon": -152.3},
    "alberta": {"label": "Alberta", "abbr": "AB", "country_scope": "canada", "lat": 53.9, "lon": -115.0},
    "arizona": {"label": "Arizona", "abbr": "AZ", "country_scope": "us", "lat": 34.1, "lon": -111.7},
    "arkansas": {"label": "Arkansas", "abbr": "AR", "country_scope": "us", "lat": 35.1, "lon": -92.4},
    "british_columbia": {"label": "British Columbia", "abbr": "BC", "country_scope": "canada", "lat": 53.7, "lon": -124.7},
    "california": {"label": "California", "abbr": "CA", "country_scope": "us", "lat": 36.7, "lon": -119.4},
    "colorado": {"label": "Colorado", "abbr": "CO", "country_scope": "us", "lat": 39.1, "lon": -105.7},
    "florida": {"label": "Florida", "abbr": "FL", "country_scope": "us", "lat": 27.8, "lon": -81.7},
    "hawaii": {"label": "Hawaii", "abbr": "HI", "country_scope": "us", "lat": 20.7, "lon": -157.5},
    "idaho": {"label": "Idaho", "abbr": "ID", "country_scope": "us", "lat": 44.2, "lon": -114.5},
    "illinois": {"label": "Illinois", "abbr": "IL", "country_scope": "us", "lat": 40.0, "lon": -89.2},
    "indiana": {"label": "Indiana", "abbr": "IN", "country_scope": "us", "lat": 39.9, "lon": -86.3},
    "kansas": {"label": "Kansas", "abbr": "KS", "country_scope": "us", "lat": 38.5, "lon": -98.4},
    "kentucky": {"label": "Kentucky", "abbr": "KY", "country_scope": "us", "lat": 37.8, "lon": -84.3},
    "louisiana": {"label": "Louisiana", "abbr": "LA", "country_scope": "us", "lat": 31.0, "lon": -91.9},
    "manitoba": {"label": "Manitoba", "abbr": "MB", "country_scope": "canada", "lat": 53.8, "lon": -98.8},
    "michigan": {"label": "Michigan", "abbr": "MI", "country_scope": "us", "lat": 44.3, "lon": -85.6},
    "mississippi": {"label": "Mississippi", "abbr": "MS", "country_scope": "us", "lat": 32.7, "lon": -89.7},
    "montana": {"label": "Montana", "abbr": "MT", "country_scope": "us", "lat": 46.9, "lon": -110.4},
    "nebraska": {"label": "Nebraska", "abbr": "NE", "country_scope": "us", "lat": 41.5, "lon": -99.7},
    "nevada": {"label": "Nevada", "abbr": "NV", "country_scope": "us", "lat": 38.8, "lon": -116.4},
    "new_mexico": {"label": "New Mexico", "abbr": "NM", "country_scope": "us", "lat": 34.4, "lon": -106.1},
    "new_york": {"label": "New York", "abbr": "NY", "country_scope": "us", "lat": 42.9, "lon": -75.5},
    "newfoundland_and_labrador": {"label": "Newfoundland and Labrador", "abbr": "NL", "country_scope": "canada", "lat": 53.1, "lon": -57.7},
    "nl_offshore": {"label": "NL Offshore", "abbr": "OFF", "country_scope": "canada", "lat": 47.8, "lon": -48.0},
    "north_dakota": {"label": "North Dakota", "abbr": "ND", "country_scope": "us", "lat": 47.5, "lon": -100.4},
    "nova_scotia": {"label": "Nova Scotia", "abbr": "NS", "country_scope": "canada", "lat": 45.0, "lon": -63.0},
    "ohio": {"label": "Ohio", "abbr": "OH", "country_scope": "us", "lat": 40.4, "lon": -82.8},
    "oklahoma": {"label": "Oklahoma", "abbr": "OK", "country_scope": "us", "lat": 35.6, "lon": -97.5},
    "oregon": {"label": "Oregon", "abbr": "OR", "country_scope": "us", "lat": 43.8, "lon": -120.6},
    "pennsylvania": {"label": "Pennsylvania", "abbr": "PA", "country_scope": "us", "lat": 41.0, "lon": -77.7},
    "saskatchewan": {"label": "Saskatchewan", "abbr": "SK", "country_scope": "canada", "lat": 54.5, "lon": -106.0},
    "south_dakota": {"label": "South Dakota", "abbr": "SD", "country_scope": "us", "lat": 44.4, "lon": -100.3},
    "texas": {"label": "Texas", "abbr": "TX", "country_scope": "us", "lat": 31.4, "lon": -99.3},
    "utah": {"label": "Utah", "abbr": "UT", "country_scope": "us", "lat": 39.3, "lon": -111.7},
    "virginia": {"label": "Virginia", "abbr": "VA", "country_scope": "us", "lat": 37.6, "lon": -78.7},
    "west_virginia": {"label": "West Virginia", "abbr": "WV", "country_scope": "us", "lat": 38.6, "lon": -80.6},
    "wyoming": {"label": "Wyoming", "abbr": "WY", "country_scope": "us", "lat": 43.0, "lon": -107.6},
}

SPECIAL_LABELS = {
    "ardmore_woodford": "Ardmore Woodford",
    "arkoma_woodford": "Arkoma Woodford",
    "cana_woodford": "Cana-Woodford",
    "dj-niobrara": "DJ-Niobrara",
    "eagle_ford": "Eagle Ford",
    "granite_wash": "Granite Wash",
}
